# Generated by Django 6.1 on 2026-08-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("littleLemonAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.URLField(blank=True),
        ),
    ]
